[package]
name = "brainlube"
version = "0.1.0"
authors = ["atil <atilkurtulmus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
fxhash = "0.2.1"
llvm-sys = "110"
libc = "^0"